### ISSUE TITLE
Add Donor Name in Path

### ISSUE THREAD

**Issue by parvez** [FoldingCommunity/fah-stats-front-end#65]
https://stats.foldingathome.org/donor/123456
https://stats.foldingathome.org/donor/id/123456
https://stats.foldingathome.org/donor/name/donorName

**Comment by toTOWfr** [comment]
Is it possible to keep the same URLs as before to maintain compatibility with older links ?

It means that both https://stats.foldingathome.org/donor/123456 and https://stats.foldingathome.org/donor/donorName would lead to the same results.

**Comment by ReadyPlayerEmma** [comment]
> 
> 
> Is it possible to keep the same URLs as before to maintain compatibility with older links ?
> 
> It means that both https://stats.foldingathome.org/donor/123456 and https://stats.foldingathome.org/donor/donorName would lead to the same results.

We'll actually be primarily moving to these URLs:
https://stats.foldingathome.org/donor/id/123456
https://stats.foldingathome.org/donor/name/donorName

But there will be redirects for the previous name URLs once lookup by name is implemented. One of the reasons it isn't there now, is that the new API didn't allow lookup by name when this page was created, so we would have needed to query the API twice, once to resolve the name to ID, and then again to get the data. The old stats site handled it differently, as there were totally separate APIs. It looks like the new API has since added support for lookups by names though.

@jcoffland I am seeing some issues with looking up users by name when there is a space in the username though:
https://api2.foldingathome.org/user/ASURC%20Agave_rc_g1%20cascade_4v100
https://api2.foldingathome.org/uid/93291534

UID is fine, but by name doesn't return the right information. However, when searching for the name we do get the basic info:
https://api2.foldingathome.org/search/user?query=ASURC%20Agave_rc_g1%20cascade_4v100

But the search API result omits a lot of the information compared to the UID lookup.

**Comment by jcoffland** [comment]
This is working correctly.
